from typing import Protocol
from uuid import UUID

from core.entities import HHAccount


class HHAccountRepositoryProtocol(Protocol):
    async def get_by_hh_user_id(self, *, hh_user_id: str) -> HHAccount | None: ...
    async def get(self, *, user_id: UUID, account_id: UUID) -> HHAccount | None: ...
    async def list(self, *, user_id: UUID) -> list[HHAccount]: ...
    async def save(self, *, account: HHAccount) -> HHAccount: ...
    async def delete(self, *, user_id: UUID, account_id: UUID) -> bool: ...
