# Deployment settings
name: haintly-profile-service
componentsLabel: haintly-profile-service
replicaCount: 1
namespace: haintly

# App settings
secretName: haintly-profile-service-secret
containerPort: 8000
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

# Image settings
image: ghcr.io/igor-526/haintly_profile-service
imagePullSecertName: ghcr-secret
imageTag: latest

migration:
  command: ["uv", "run", "alembic", "-c", "alembic.ini", "upgrade", "head"]
  workingDir: /app/src